import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst, CacheFirst } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";
import { CacheableResponsePlugin } from "workbox-cacheable-response";

// Precaches all static build assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Network-First strategy for backend API requests (/api/*)
registerRoute(
  /^https?:\/\/.*\/api\/.*/i,
  new NetworkFirst({
    cacheName: "api-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 24 * 60 * 60, // 24 Hours
      }),
    ],
    networkTimeoutSeconds: 5,
  })
);

// CacheFirst strategy for OpenStreetMap map tiles
registerRoute(
  /^https:\/\/[a-c]\.tile\.openstreetmap\.org\/.*/i,
  new CacheFirst({
    cacheName: "map-tiles-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// Custom WakeStop Alarm Notification Handler
self.addEventListener("message", (event) => {
  if (!event.data) return;
  const { type, title, body, stage } = event.data;

  if (type === "TRIGGER_ALARM_NOTIFICATION") {
    const isCritical = stage === "critical";
    const vibratePattern = isCritical
      ? [600, 100, 600, 100, 600, 100, 900]
      : [400, 150, 400, 150, 400];

    event.waitUntil(
      self.registration.showNotification(title || "⏰ WakeStop Alarm!", {
        body: body || "Your stop is approaching! Wake up now.",
        icon: "/pwa-192x192.png",
        badge: "/pwa-192x192.png",
        tag: "wakestop-alarm",
        renotify: true,
        requireInteraction: true,
        silent: false,
        vibrate: vibratePattern,
        actions: [
          { action: "acknowledge", title: "✅ I'm Awake" },
          { action: "snooze", title: "⏳ 2 Min Snooze" },
        ],
        data: { stage, timestamp: Date.now() },
      })
    );
  }

  if (type === "DISMISS_ALARM_NOTIFICATION") {
    event.waitUntil(
      self.registration
        .getNotifications({ tag: "wakestop-alarm" })
        .then((list) => list.forEach((n) => n.close()))
    );
  }
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const { action } = event;

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clients) => {
        for (const client of clients) {
          if (action === "acknowledge") {
            client.postMessage({ type: "ALARM_ACKNOWLEDGED" });
          } else if (action === "snooze") {
            client.postMessage({ type: "ALARM_SNOOZED", snoozeMs: 120000 });
          } else {
            if ("focus" in client) client.focus();
          }
        }
        if (clients.length === 0) {
          return self.clients.openWindow("/");
        }
      })
  );
});
